### ISSUE TITLE
Error within `streamFactory` causes unhandled promise rejection

### ISSUE THREAD

**Issue by amydevs** [MatrixAI/js-rpc#62]
### Describe the bug

Any rejected promise returned by the streamFactory function will cause an unhandled promise rejection, even when the caller handles all exceptions.

### To Reproduce

```ts
test('streamFactory error propagation', async () => {
      const rpcClient = new RPCClient({
        manifest: {},
        streamFactory: () => Promise.reject(new Error("streamFactory error")),
        logger,
        idGen,
      });
      try {
        await rpcClient.unaryCaller(methodName, {}).catch(() => {});
      }
      catch(e) {
      }
    });
```

### Expected behavior

The error should be able to be caught by the caller.

### Screenshots

```
/home/amy/git/js-rpc/tests/RPCClient.test.ts:1245
            const error = new Error('streamFactory error');
                          ^
 
Error: streamFactory error
    at Object. (/home/amy/git/js-rpc/tests/RPCClient.test.ts:1245:27)
    at Promise.then.completed (/home/amy/git/js-rpc/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise ()
    at callAsyncCircusFn (/home/amy/git/js-rpc/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/home/amy/git/js-rpc/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/home/amy/git/js-rpc/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/home/amy/git/js-rpc/node_modules/jest-circus/build/run.js:97:9)
    at _runTestsForDescribeBlock (/home/amy/git/js-rpc/node_modules/jest-circus/build/run.js:91:9)
    at _runTestsForDescribeBlock (/home/amy/git/js-rpc/node_modules/jest-circus/build/run.js:91:9)
```

### Additional context

[https://gitlab.com/MatrixAI/Engineering/Polykey/Polykey-Network-Status/-/merge_requests/22#note_1806676003](https://gitlab.com/MatrixAI/Engineering/Polykey/Polykey-Network-Status/-/merge_requests/22#note_1806676003)

### Notify maintainers

@amydevs 
@tegefaulkes

**Comment by amydevs** [comment]
hjhjhj

**Comment by tegefaulkes** [comment]
Testing...

**Comment by tegefaulkes** [comment]
Testing @amy.yan
